### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by doritiosemdesiat** [Pold87/academic-keyword-occurrence#1]
I'm new to Python; installed 2.7.11 and beautiful soup 4 but getting the following error (image below). Any suggestions please?
![image](https://cloud.githubusercontent.com/assets/19581868/15561511/8e013a30-22ab-11e6-9837-755a7fc60cdb.png)

**Comment by Pold87** [comment]
It looks like you are trying to call the script in Python's interactive mode (that is, you started Python first and then you are executing the command). 
However, the command should be executed using the command-line interface of your operating system (that is, you directly call Python with the specified arguments).

**Comment by doritiosemdesiat** [comment]
Awesome, thank you! Works great now.
