### ISSUE TITLE
No module named 'urllib2'

### ISSUE THREAD

**Issue by muranava** [Pold87/academic-keyword-occurrence#10]
hi
am on OSX and getting the following error:
----
  File "extract_occurrences.py", line 5, in <module>
    from urllib2 import Request, build_opener, HTTPCookieProcessor
ModuleNotFoundError: No module named 'urllib2'
-------
thx

**Comment by Pold87** [comment]
Hi,
Are you using the Python 2 or Python 3 branch? Have you installed urllib2
via pip?

**Comment by muranava** [comment]
hi
using python 3

according to this - https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2

there'e been a change in urllib2 module?

**Comment by muammar** [comment]
It is solved now by #12.
