### ISSUE TITLE
feature request： could you make a timeline by searching the keyword sets

### ISSUE THREAD

**Issue by dvdface** [Pold87/academic-keyword-occurrence#23]
could you make a timeline by searching the keyword sets

list the most cited paper or books , and abstract the keywords from it 

then make a timelien for this keywords and put paper list under it.

**Comment by Pold87** [comment]
Sorry, even though this feature would certainly be useful, I have no plans to implement it: first because I would like to keep the tool simple, second because I am lacking the time to implement this feature.
