### ISSUE TITLE
Searching multiple keywords

### ISSUE THREAD

**Issue by gsaponaro** [Pold87/academic-keyword-occurrence#4]
Hi @Pold87, thanks for the cool script! I found it in [this answer](https://academia.stackexchange.com/a/63511/76452) on Academia SE.

Do I understand correctly that, if I search for >1 keyword, the output is the occurrence of all the keywords?

For example, I want to observe the trend of a keyword in research (e.g., lasers), but that keyword is a really common word, thus I want to restrict the search to a second keyword or field (e.g., robots).

```
$ python extract_occurrences.py 'lasers' 2016 2017
year,results
2016,42900
2017,28000
$ python extract_occurrences.py 'lasers robots' 2016 2017
year,results
2016,1640
2017,713
```
^ Basically, I wonder if the second example is the result of searching for lasers AND robots on Google Scholar, per year.

**Comment by Pold87** [comment]
Thank you!
Yes, it displays the results of lasers AND robots, in the same way as if you'd type 'lasers robots' into Google Scholars search bar. You can also verify the number of results by a manual Google Scholar search:
https://scholar.google.de/scholar?q=lasers+robots&btnG=&hl=de&as_sdt=1%2C5&as_ylo=2016&as_yhi=2016&as_vis=1
