### ISSUE TITLE
Quoted strings

### ISSUE THREAD

**Issue by caedmon5** [Pold87/academic-keyword-occurrence#7]
Hi,

This is really great!

The one thing I'd love to see, but just don't have the programming for, is being able to double quote a collocation string. I.e. currently 'this that' seems to search for q=this+that (without quotations). I'd like to be able to search for q="this+that".

I've tried experimenting with different ways of introducing double quotes into the search string (e.g. '"...'", or '\"...\"', or '%22...%22', but can't get anything to return the expected results.

Being able to do this would be great because it means you could deal with phrases, words that are commonly broken up in english orthography (e.g. high school) or author names.

**Comment by Pold87** [comment]
Hi,

Thank you!
To introduce double quotes, you have to escape the quotes with a backslash; for example:

python extract_occurrences.py '\"bitcoin mining\"' 2014 2015

**Comment by caedmon5** [comment]
Thank you very much. I'd tried that, but I get an error. Here's some examples:


python extract_occurrences.py '\"Global Outlook Digital Humanities\"' 2010 2016
year,results
Traceback (most recent call last):
  File "extract_occurrences.py", line 72, in <module>
    html = get_range(search_term, start_date, end_date)
  File "extract_occurrences.py", line 48, in get_range
    num_results, success = get_num_results(search_term, date, date)
  File "extract_occurrences.py", line 31, in get_num_results
    num_results = ''.join(res[0]) # convert string to number
IndexError: list index out of range

And using a syntax similar to non-escaped example you give:


python extract_occurrences.py '"Global Outlook Digital Humanities"' 2010 2011
year,results
Traceback (most recent call last):
  File "extract_occurrences.py", line 72, in <module>
    html = get_range(search_term, start_date, end_date)
  File "extract_occurrences.py", line 48, in get_range
    num_results, success = get_num_results(search_term, date, date)
  File "extract_occurrences.py", line 31, in get_num_results
    num_results = ''.join(res[0]) # convert string to number
IndexError: list index out of range





[U of Lethbridge Logo]


Daniel Paul O'Donnell

Professor of English and Associate Member of the University Library Academic Staff

Editor, Digital Studies/Le champ num<http://digitalstudies.org/>érique
<http://digitalstudies.org/>

Vice President, Force 11<http://force11.org>

Department of English and University Library

University of Lethbridge

4401 University Drive West

Lethbridge AB T1K 3M4

Canada

Tel. +1 (403) 329-2377


http://people.uleth.ca/~daniel.odonnell

@danielPaulOD

________________________________

**Comment by caedmon5** [comment]
Thank you very much. I'd tried that, but I get an error. Here's some examples:

python extract_occurrences.py '\"Global Outlook Digital Humanities\"' 2010 2016
year,results
Traceback (most recent call last):
  File "extract_occurrences.py", line 72, in <module>
    html = get_range(search_term, start_date, end_date)
  File "extract_occurrences.py", line 48, in get_range
    num_results, success = get_num_results(search_term, date, date)
  File "extract_occurrences.py", line 31, in get_num_results
    num_results = ''.join(res[0]) # convert string to number
IndexError: list index out of range

And using a syntax similar to non-escaped example you give:

python extract_occurrences.py '"Global Outlook Digital Humanities"' 2010 2011
year,results
Traceback (most recent call last):
  File "extract_occurrences.py", line 72, in <module>
    html = get_range(search_term, start_date, end_date)
  File "extract_occurrences.py", line 48, in get_range
    num_results, success = get_num_results(search_term, date, date)
  File "extract_occurrences.py", line 31, in get_num_results
    num_results = ''.join(res[0]) # convert string to number
IndexError: list index out of range

**Comment by Pold87** [comment]
Thanks for your reply. I think it's not the quoted string that causes the problem but the fact that there are no search results for "Global Outlook Digital Humanities" for 2010 - 2012 (https://scholar.google.com/scholar?q=%22Global+Outlook+Digital+Humanities%22&hl=en&as_sdt=1%2C5&as_vis=1&as_ylo=2010&as_yhi=2012).

Could you maybe check whether
`python extract_occurrences.py '\"Global Outlook Digital Humanities\"' 2013 2016`
works for you (2013 - 2016)?

I'll look into the other problem (i.e., when the number of search results is 0).

**Comment by Pold87** [comment]
I fixed the other problem now (when the number of results is 0). Therefore, 
`python extract_occurrences.py '\"Global Outlook Digital Humanities\"' 2010 2016`
should work fine now.

**Comment by gpintarelli** [comment]
Amazing code guys! It will be very helpfull to me.

Thank you,

**Comment by gsaponaro** [comment]
Hi @Pold87, I now get the same result regardless of escaping the double quotes or not. Is it the expected behaviour? In that case, I will just use the second alternative (i.e., without the \) as it is simpler.

```
$ python extract_occurrences.py '\"Global Outlook Digital Humanities\"' 2010 2016
year,results
2010,0
2011,0
2012,0
2013,8
2014,11
2015,20
2016,20
$ python extract_occurrences.py '"Global Outlook Digital Humanities"' 2010 2016
year,results
2010,0
2011,0
2012,0
2013,8
2014,11
2015,20
2016,20

```

**Comment by Pold87** [comment]
Hi @gsaponaro ,  thanks for your comment, yes this is the expected behavior. You actually don't need to escape the double quotes if you put them inside the single quotes and you can just use the second alternative.

**Comment by flavio75** [comment]
Great code! Thanks for sharing it!
Do you have any suggestion how to cite the repository (or the code) in a scientific paper?
Do you have a DOI or did linked it to Zenodo or something similar?

**Comment by caedmon5** [comment]
Really, this should use the Zenodo<-->github connection. Then you get a DOI for each release of the github repository!




[U of Lethbridge Logo]


Daniel Paul O'Donnell

Professor

Chief Spokesperson (Bargaining), University of Lethbridge Faculty Association

Editor, Digital Studies/Le champ num<http://digitalstudies.org/>érique
<http://digitalstudies.org/>

Vice President, Force 11<http://force11.org>

Department of English and University Library

University of Lethbridge

4401 University Drive West

Lethbridge AB T1K 3M4

Canada

Tel. +1 (403) 329-2377


http://people.uleth.ca/~daniel.odonnell

@danielPaulOD

________________________________

**Comment by Pold87** [comment]
@flavio75 @caedmon5  Thanks a lot for pointing out Zenodo. I linked the repository to Zenodo now http://doi.org/10.5281/zenodo.1218409).
